# Generated by Django 6.0.6 on 2026-06-21 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_kitchen_station_menuitem_default_priority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='est_time',
            field=models.PositiveIntegerField(blank=True, help_text='Write estimated preparation time in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('ps', 'Partially Served'), ('s', 'Served'), ('b', 'Billed')], default='p', max_length=2),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('ps', 'Partially Served'), ('s', 'Served'), ('b', 'Billed')]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('p', 'Preparing'), ('r', 'Ready'), ('s', 'Served')], default='p', max_length=2),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='orders.kitchenstation'),
        ),
        migrations.DeleteModel(
            name='KITCHEN_STATION',
        ),
    ]
