# Generated by Django 6.0.6 on 2026-07-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_kitchenstation_alter_menuitem_est_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('p', 'Preparing'), ('ps', 'Partially Served'), ('r', 'Ready'), ('s', 'Served')], default='p', max_length=2),
        ),
    ]
